<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access denied.' => '',
    'Incorrect username or password.' => '',
    'Invalid authentication token.' => '',
    'Page not found.' => '',
    'Something went wrong.' => '',
    'There is no account is associated with this e-mail address.' => '',
    'You have already used this password.' => '',
    'Your account has been locked due to too many failed login attempts.' => '',
    'Your account has not yet been activated.' => '',
    '{attribute} is too short, minimum is {n} {n, plural, =1{character} other{characters}}.' => '',
    '{attribute} should contain at least {n} lower case {n, plural, =1{character} other{characters}}.' => '',
    '{attribute} should contain at least {n} non alpha numeric {n, plural, =1{character} other{characters}}.' => '',
    '{attribute} should contain at least {n} upper case {n, plural, =1{character} other{characters}}.' => '',
    '{attribute} should contain at least {n} {n, plural, =1{digit} other{digits}}.' => '',
];
