<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Change Password' => '',
    'Change password' => '',
    'Create Account' => '',
    'Do not worry' => '',
    'Forgot password' => '',
    'If you already have an account &ndash; {loginLink}.' => '',
    'If you do not have an account &mdash; {signupLink}.' => '',
    'If you forgot your password you can {link}.' => '',
    'Log in' => '',
    'Login' => '',
    'Please enter a new password twice to change the your password.' => '',
    'Please enter your e-mail address and we will send you instructions on how to reset your password.' => '',
    'Recover Account' => '',
    'Reset password' => '',
    'Sign up' => '',
    'Success' => '',
    'Thank you for registering!' => '',
    'You have requested to reset your password.' => '',
    'You will soon receive an email with instructions on how to activate your account.' => '',
    'You will soon receive an email with instructions on how to reset the password for your account.' => '',
    'Your password has expired.' => '',
];
