<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access denied.' => 'Pääsy evätty.',
    'Incorrect username or password.' => 'Väärä käyttäjänimi tai salasana.',
    'Invalid authentication token.' => 'Virheellinen tunnistus avain.',
    'Page not found.' => 'Sivua ei löydy.',
    'Something went wrong.' => 'Jotain meni pieleen.',
    'There is no account is associated with this e-mail address.' => '',
    'You have already used this password.' => 'Olet jo käyttänyt tämän salasanan.',
    'Your account has been locked due to too many failed login attempts.' => '',
    'Your account has not yet been activated.' => 'Et ole vielä aktivoinut tiliäsi.',
    '{attribute} is too short, minimum is {n} {n, plural, =1{character} other{characters}}.' => '{attribute} on liian lyhyt, minimi on {n} {n, plural, =1{merkki} other{merkkiä}}.',
    '{attribute} should contain at least {n} lower case {n, plural, =1{character} other{characters}}.' => '{attribute} tulee sisältää ainakin {n} pientä kirjainta {n, plural, =1{merkki} other{merkkiä}}.',
    '{attribute} should contain at least {n} non alpha numeric {n, plural, =1{character} other{characters}}.' => '{attribute} tulee sisältää ainakin {n} merkkiä {n, plural, =1{merkki} other{merkkiä}}.',
    '{attribute} should contain at least {n} upper case {n, plural, =1{character} other{characters}}.' => '{attribute} tulee sisältää ainakin {n} isoa kirjainta {n, plural, =1{merkki} other{merkkiä}}.',
    '{attribute} should contain at least {n} {n, plural, =1{digit} other{digits}}.' => '{attribute} tulee sisältää ainakin {n} {n, plural, =1{numero} other{numeroa}}.',
];
