<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '# Failed Attempts' => 'Epäonnistuneet Yritykset',
    'Account ID' => 'Tili ID',
    'Authentication Key' => 'Tunnistus Avain',
    'Client ID' => 'Toimeksiantaja ID',
    'Created At' => 'Luotu',
    'Data' => 'Data',
    'Email' => 'Sähköposti',
    'ID' => 'ID',
    'Last Login At' => 'Viimeksi kirjautunut',
    'Name' => 'Nimi',
    'Password' => 'Salasana',
    'Remember me' => 'Muista minut',
    'Status' => 'Status',
    'Success' => 'Onnistui',
    'Token' => 'Avain',
    'Type' => 'Tyyppi',
    'Username' => 'Käyttäjänimi',
    'Verification Code' => 'Vahvistuskoodi',
    'Verify Password' => 'Vahvista Salasana',
];
