<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Change Password' => 'Vaihda salasana',
    'Connect' => 'Yhdistä',
    'Connect with {provider}' => 'Yhdistä {provider}',
    'Create Account' => 'Rekisteröidy',
    'Did you forget your password? &mdash; {forgotLink}.' => 'Unohditko salasanasi? &mdash; {forgotLink}.',
    'Done' => 'Valmis',
    'Forgot Password' => 'Salasana hukassa?',
    'If you already have an account &mdash; {loginLink}.' => 'Jos sinulla on jo tili &mdash; {loginLink}.',
    'If you do not have an account &mdash; {signupLink}.' => 'Jos sinulla ei vielä ole tiliä &mdash; {signupLink}.',
    'Login' => 'Kirjaudu',
    'Please enter a new password twice to change the your password.' => 'Ole hyvä ja syötä uusi salasana kahdesti.',
    'Please enter the verification code in the field above.' => 'Ole hyvä ja syötä vahvistuskoodi alle olevaan kenttään.',
    'Please enter your e-mail address and desired username and to create your account.' => 'Ole hyvä ja syötä sähköpostiosoitteesi ja haluamasi käyttäjänimen luodaksesi tilisi.',
    'Please enter your e-mail address and we will send you instructions on how to reset your password.' => 'Ole hyvä ja syötä sähköpostiosoitteesti ja lähetämme sinulle ohjeet miten voit uusia salasanansi.',
    'Recover Account' => 'Lähetä',
    'Recover it' => 'Uusi salasanasi',
    'Reset Password' => 'Uusi salasana',
    'Sign up' => 'Rekisteröidy',
    'Sign up successfull' => 'Rekisteröityminen onnistui',
    'You have requested to reset your password.' => 'Olet pyytänyt salasanan uusimista.',
    'You may also log in using one of the providers below:' => 'Voit myös kirjautua käyttäen yhtä alla mainituista palveluista:',
    'You will soon receive an email with instructions on how to activate your account.' => 'Saat pian sähköpostiisi tilisi aktivoimisohjeet.',
    'You will soon receive an email with instructions on how to reset the password for your account.' => 'Saat pian sähköpostiisi salasanan uusimisohjeet.',
    'Your password has expired.' => 'Salasanasi on vanhentunut.',
];
